/** A subset of the CSS variables VS Code injects into webviews, for Dark Modern and Light Modern. */
const common: Record<string, string> = {
  'font-family': '-apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, "Ubuntu", sans-serif',
  'font-size': '13px',
  'editor-font-family': '"Droid Sans Mono", "DejaVu Sans Mono", monospace',
  'editor-font-size': '13px',
  'editor-font-weight': 'normal',
  'charts-red': '#f14c4c',
  'charts-green': '#89d185',
  'charts-yellow': '#cca700',
  'charts-orange': '#d18616',
};

const dark: Record<string, string> = {
  ...common,
  foreground: '#cccccc',
  descriptionForeground: '#9d9d9d',
  'editor-background': '#1f1f1f',
  'editor-foreground': '#cccccc',
  'editorLineNumber-foreground': '#6e7681',
  'editorLineNumber-activeForeground': '#cccccc',
  'sideBar-background': '#181818',
  'panel-border': '#2b2b2b',
  focusBorder: '#0078d4',
  'toolbar-hoverBackground': '#5a5d5e50',
  'icon-foreground': '#cccccc',
  'inputOption-activeBackground': '#2489db82',
  'inputOption-activeBorder': '#2488db',
  'inputOption-activeForeground': '#ffffff',
  'checkbox-background': '#313131',
  'checkbox-border': '#3c3c3c',
  'checkbox-foreground': '#cccccc',
  'scrollbarSlider-background': '#79797966',
  'scrollbarSlider-hoverBackground': '#646464b3',
  'editorHoverWidget-background': '#202020',
  'editorHoverWidget-border': '#454545',
  'editorHoverWidget-foreground': '#cccccc',
  'editorWidget-background': '#202020',
  'editorWidget-border': '#313131',
  'widget-shadow': '#0000005c',
  'button-background': '#0078d4',
  'button-foreground': '#ffffff',
  'button-hoverBackground': '#026ec1',
  'button-secondaryBackground': '#313131',
  'button-secondaryForeground': '#cccccc',
  'button-secondaryHoverBackground': '#3c3c3c',
  'badge-background': '#616161',
  'badge-foreground': '#f8f8f8',
  'textLink-foreground': '#4daafc',
  'diffEditor-insertedTextBackground': '#9ccc2c33',
  'diffEditor-removedTextBackground': '#ff000033',
  'diffEditor-insertedLineBackground': '#9bb95533',
  'diffEditor-removedLineBackground': '#ff000033',
  'keybindingLabel-background': '#8080802b',
  'keybindingLabel-foreground': '#cccccc',
  'keybindingLabel-border': '#33333399',
  'notifications-background': '#1f1f1f',
  'errorForeground': '#f85149',
};

const light: Record<string, string> = {
  ...common,
  foreground: '#3b3b3b',
  descriptionForeground: '#3b3b3b',
  'editor-background': '#ffffff',
  'editor-foreground': '#3b3b3b',
  'editorLineNumber-foreground': '#6e7681',
  'editorLineNumber-activeForeground': '#171184',
  'sideBar-background': '#f8f8f8',
  'panel-border': '#e5e5e5',
  focusBorder: '#005fb8',
  'checkbox-background': '#f8f8f8',
  'checkbox-border': '#cecece',
  'checkbox-foreground': '#3b3b3b',
  'toolbar-hoverBackground': '#b8b8b850',
  'icon-foreground': '#3b3b3b',
  'inputOption-activeBackground': '#bed6ed',
  'inputOption-activeBorder': '#005fb8',
  'inputOption-activeForeground': '#000000',
  'scrollbarSlider-background': '#64646466',
  'editorHoverWidget-background': '#f8f8f8',
  'editorHoverWidget-border': '#c8c8c8',
  'editorHoverWidget-foreground': '#3b3b3b',
  'editorWidget-background': '#f8f8f8',
  'editorWidget-border': '#e5e5e5',
  'widget-shadow': '#00000029',
  'button-background': '#005fb8',
  'button-foreground': '#ffffff',
  'button-secondaryBackground': '#e5e5e5',
  'button-secondaryForeground': '#3b3b3b',
  'badge-background': '#cccccc',
  'badge-foreground': '#3b3b3b',
  'textLink-foreground': '#005fb8',
  'diffEditor-insertedTextBackground': '#9ccc2c40',
  'diffEditor-removedTextBackground': '#ff000033',
  'charts-red': '#e51400',
  'charts-green': '#388a34',
  'charts-yellow': '#bf8803',
};

function style(vars: Record<string, string>): string {
  return Object.entries(vars)
    .map(([k, v]) => `--vscode-${k}: ${v.replace(/"/g, '&quot;')};`)
    .join(' ');
}

export const THEMES = {
  dark: { bodyClass: 'vscode-dark', style: style(dark) },
  light: { bodyClass: 'vscode-light', style: style(light) },
};
